### ISSUE TITLE
Empty web interface

### ISSUE THREAD

**Issue by batwishpers** [ReachFive/fake-smtp-server#1]
Hi,

The web UI do not render emails stored. (Just a blank page with only Email written)
The web view filtered by address return a 404 :(.
I can retrieve them using the rest interface.

Otherwise, this app is great and really simple to install :)
I looked the code, but am not familiar with node, so I did not really understand where the emails are lost. 

Running on node v8.6.0

**Comment by jcdelmas** [comment]
Hi,

Thank you for your message.
I made some improvements to the app. There was also some errors in the documentation.

If you try the last version, can you tell me if your problem is still present ?

**Comment by batwishpers** [comment]
Hi!
Thanks for the update ! The web interface is working fine now.
It is as expected, simple and clear :)

Just a small note, there is still a small mistake in log:
`INFO:` HTTP server listening on port 1080, e-mails are available on /emails.`

**Comment by dpupovModelN** [comment]
UI still is empty 
npm install -g fake-smtp-server
/usr/bin/fake-smtp-server -> /usr/lib/node_modules/fake-smtp-server/index.js
/usr/lib
└─ fake-smtp-server@0.7.6
