### ISSUE TITLE
404 when trying to remove all messages via API

### ISSUE THREAD

**Issue by levmixali4** [ReachFive/fake-smtp-server#3]
Using Postman I'm sending `DELETE http://localhost:1080/api/emails`
the response is:
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Cannot DELETE /api/emails</pre>
    </body>
</html>
```

Please note `GET http://localhost:1080/api/emails` works fine

**Comment by jcdelmas** [comment]
Sorry, I can't reproduce this.

Are you sure you are running the last version ?

**Comment by levmixali4** [comment]
yeah, not reproduced on latest version. Thanks.
