### ISSUE TITLE
Headers aren't properly serialized to JSON

### ISSUE THREAD

**Issue by bioball** [ReachFive/fake-smtp-server#7]
Great module! However, I'm noticing that the headers aren't being properly serialized to JSON.

`simpleParser` turns the headers into a `Map` object, and when `Map`'s are JSON-stringified, they get serialized as `"{}"`, regardless of whether there's data in the map or not. There should be some extra logic that deals with how to serialize these.

This link should be helpful:
http://2ality.com/2015/08/es6-map-json.html

**Comment by jcdelmas** [comment]
Thanks !

In fact, informations present in headers map are already available in the root object (from, to, date...). So I chose to delete it rather than parsing it.

I hope this is not a problem for you.

**Comment by bioball** [comment]
It is a problem unfortunately, as I'm sending custom mail headers, and am trying to write tests around them :(

I'd be happy to send a PR for this if you want.

**Comment by jcdelmas** [comment]
Oh sorry. Don't hesitate to make a PR. To avoid document overload, you can add an option to enable headers serialization only when necessary.

**Comment by bioball** [comment]
Done!

**Comment by bioball** [comment]
Thanks for merging the PR! Can you publish a new version of this module?

**Comment by jcdelmas** [comment]
Done !

**Comment by bioball** [comment]
Great, thanks!
