### ISSUE TITLE
Error: Mail command failed: 421 Error: too many unauthenticated commands

### ISSUE THREAD

**Issue by sourabh8003** [ReachFive/fake-smtp-server#9]
## Feature request (Bugfix)

**Current Behaviour**
While sending emails through automated test cases to `fake-smtp-server`  after few successful deliveries it's started throwing an error that `Mail command failed: 421 Error: too many unauthenticated commands` due to the spam emails filtering condition for unauthenticated users or clients, this is `nodemailer` configuration option, which is not implemented yet in this package. 

Resulting it's not allowing us to send email to the SMTP server, even if we pass the authentication credentials to the configuration it only works for the `API` calls to fetch the emails but not for SMTP server.

**Desired behavior**
We can pass one property with `fake-smtp-server` start command to set nodemailer's `maxAllowedUnauthenticatedCommands`.

I will create a PR for the proposed fixes.

**Comment by sourabh8003** [comment]
#10 PR to fix the above issue.

**Comment by vatioz** [comment]
Is there any workaround to this issue? Restart doesn't work, I am not able to send any more emails.

I noticed your PR, but it seems nobody else did... :(
